# Generated by Django 3.1.7 on 2021-03-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Eno', models.AutoField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=30)),
                ('Esalary', models.BigIntegerField()),
            ],
        ),
    ]
